[build]
builder = "railpack"

[deploy]
startCommand = "python youtube_clone/manage.py collectstatic --noinput && python youtube_clone/manage.py migrate && gunicorn --chdir youtube_clone youtube_clone.wsgi:application"