# Generated by Django 5.1.5 on 2025-02-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("thumbnail", models.ImageField(upload_to="videos/thumbnails")),
                ("video_file", models.FileField(upload_to="videos/video_files/")),
                ("description", models.TextField()),
                (
                    "upload_date",
                    models.DateTimeField(default="2025-02-16T20:49:04.999351"),
                ),
                ("author", models.CharField(max_length=100)),
                ("views", models.IntegerField()),
                ("likes", models.IntegerField()),
                ("dislikes", models.IntegerField()),
            ],
            options={
                "db_table": "videos",
            },
        ),
    ]
