# Generated by Django 5.1.5 on 2025-02-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="video",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="video",
            name="upload_date",
            field=models.DateTimeField(default="2025-02-16T20:49:47.357087"),
        ),
        migrations.AlterField(
            model_name="video",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
