# Generated by Django 5.1.5 on 2025-02-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0002_alter_video_dislikes_alter_video_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="author",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="video",
            name="upload_date",
            field=models.DateTimeField(default="2025-02-16T21:42:54.821509"),
        ),
    ]
