# Generated by Django 5.1.5 on 2025-03-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0002_remove_video_author_video_author_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="author_id",
            new_name="author",
        ),
    ]
