# Generated by Django 5.1.5 on 2025-03-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0006_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="restriction",
            field=models.CharField(
                choices=[("none", "None"), ("age", "Age"), ("copyright", "Copyright")],
                default="None",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="type",
            field=models.CharField(
                choices=[("video", "Video"), ("shorts", "Shorts")],
                default="Video",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("protected", "Protected"),
                ],
                default="Public",
                max_length=10,
            ),
        ),
    ]
