# Generated by Django 5.1.5 on 2025-02-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0008_user_playlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="author",
            field=models.IntegerField(),
        ),
    ]
