# Generated by Django 5.1.5 on 2025-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0008_playlist_number_of_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("protected", "Protected"),
                ],
                default="Private",
                max_length=10,
            ),
        ),
    ]
