# Generated by Django 5.1.5 on 2025-04-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0009_playlist_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
