# Generated by Django 5.1.5 on 2025-04-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0010_playlist_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
