# Generated by Django 5.1.5 on 2025-03-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="subscribers",
            field=models.IntegerField(default=0),
        ),
    ]
