# Generated by Django 5.1.5 on 2025-03-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_account_subscribers"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="number_of_videos",
            field=models.IntegerField(default=0),
        ),
    ]
